import {
  useEffect,
  useState,
} from "react";

import ChatHeader from "../chat/ChatHeader";
import WelcomeScreen from "../chat/WelcomeScreen";
import MessageList from "../chat/MessageList";
import ChatComposer from "../chat/ChatComposer";

import { useChat } from "../../hooks/useChat";

import {
  getConversation,
} from "../../services/chatService";


function createConversationTitle(
  message,
  attachments = []
) {
  if (!message.trim()) {
    if (attachments.length > 0) {
      return attachments.length === 1
        ? attachments[0].name
        : `${attachments.length} attachments`;
    }

    return "New conversation";
  }

  const cleanedMessage =
    message
      .replace(/\s+/g, " ")
      .trim();

  const words =
    cleanedMessage.split(" ");

  const titleWords =
    words.slice(0, 7);

  let title =
    titleWords.join(" ");

  if (words.length > 7) {
    title += "...";
  }

  return (
    title.charAt(0).toUpperCase() +
    title.slice(1)
  );
}


function ChatLayout({
  sidebarCollapsed,
  activeConversation,
  conversations,
  onConversationUpdate,
}) {
  const [
    selectedModel,
    setSelectedModel,
  ] = useState(() => {
    return (
      localStorage.getItem(
        "nova-model"
      ) || "Nova Standard"
    );
  });


  const {
    messages,
    isLoading,
    sendUserMessage,
    regenerateMessage,
    editMessage,
    stopGeneration,
    clearChat,
    loadMessages,
  } = useChat();


  const activeConversationData =
    conversations.find(
      (conversation) =>
        conversation.id ===
        activeConversation
    );


  const conversationTitle =
    activeConversationData?.title ||
    "New conversation";


  /*
   * SAVE SELECTED MODEL
   */

  useEffect(() => {
    localStorage.setItem(
      "nova-model",
      selectedModel
    );
  }, [selectedModel]);


  /*
   * LOAD CONVERSATION
   * FROM BACKEND
   */

  useEffect(() => {
    let cancelled = false;


    const loadSelectedConversation =
      async () => {

        /*
         * No active conversation.
         */

        if (!activeConversation) {
          clearChat();
          return;
        }


        try {

          /*
           * Clear current messages
           * before loading the selected
           * conversation.
           */

          clearChat();


          /*
           * Get the complete conversation
           * from FastAPI.
           */

          const conversation =
            await getConversation(
              activeConversation
            );


          /*
           * Ignore response if the user
           * changed conversations while
           * the request was running.
           */

          if (cancelled) {
            return;
          }


          /*
           * Get messages returned
           * by the backend.
           */

          const backendMessages =
            Array.isArray(
              conversation?.messages
            )
              ? conversation.messages
              : [];


          /*
           * Put backend messages
           * into useChat.
           */

          loadMessages(
            backendMessages
          );

        } catch (error) {

          if (cancelled) {
            return;
          }


          console.error(
            "Failed to load conversation:",
            error
          );


          loadMessages([]);
        }
      };


    loadSelectedConversation();


    return () => {
      cancelled = true;
    };

  }, [
    activeConversation,
  ]);


  /*
   * CREATE FIRST CONVERSATION
   */

  const createConversation =
    async (
      message,
      attachments = []
    ) => {

      const title =
        createConversationTitle(
          message,
          attachments
        );


      /*
       * conversationId is null
       * because the backend creates
       * the conversation.
       */

      const result =
        await sendUserMessage(
          message,
          selectedModel,
          attachments,
          {
            conversationId:
              null,

            conversationTitle:
              title,

            history: [],
          }
        );


      /*
       * Stop if request failed.
       */

      if (
        !result ||
        !result.assistantMessage ||
        result.assistantMessage.role !==
        "assistant"
      ) {
        return;
      }


      /*
       * Get the real conversation ID
       * generated by the backend.
       */

      const backendConversationId =
        result.assistantMessage
          .conversation_id;


      if (
        !backendConversationId
      ) {
        console.error(
          "Backend did not return conversation_id"
        );

        return;
      }


      const now =
        new Date().toISOString();


      /*
       * Add conversation to
       * React state.
       */

      onConversationUpdate({
        id:
          backendConversationId,

        title,

        messages: [
          result.userMessage,
          result.assistantMessage,
        ],

        createdAt:
          now,

        updatedAt:
          now,
      });
    };


  /*
   * SEND MESSAGE
   */

  const handleNewMessage =
    async (
      message,
      attachments = []
    ) => {

      const trimmedMessage =
        message.trim();


      /*
       * Do not send an empty message
       * unless there is an attachment.
       */

      if (
        !trimmedMessage &&
        attachments.length === 0
      ) {
        return;
      }


      /*
       * CREATE NEW CONVERSATION
       */

      if (!activeConversation) {

        await createConversation(
          trimmedMessage,
          attachments
        );

        return;
      }


      /*
       * EXISTING CONVERSATION
       */

      const history =
        messages
          .filter(
            (item) =>
              item.role === "user" ||
              item.role === "assistant"
          )
          .map(
            (item) => ({
              role:
                item.role,

              content:
                item.content,
            })
          );


      /*
       * Send message to backend.
       */

      const result =
        await sendUserMessage(
          trimmedMessage,

          selectedModel,

          attachments,

          {
            conversationId:
              activeConversation,

            conversationTitle:
              conversationTitle,

            history,
          }
        );


      /*
       * Stop if backend request failed.
       */

      if (
        !result ||
        !result.assistantMessage ||
        result.assistantMessage.role !==
        "assistant"
      ) {
        return;
      }


      /*
       * Update the sidebar conversation
       * immediately.
       */

      const now =
        new Date().toISOString();


      onConversationUpdate({

        ...(activeConversationData || {}),

        id:
          activeConversation,

        title:
          conversationTitle,

        messages: [
          ...messages,

          result.userMessage,

          result.assistantMessage,
        ],

        updatedAt:
          now,
      });
    };


  /*
   * REGENERATE
   */

  const handleRegenerate =
    async (message) => {

      if (isLoading) {
        return;
      }


      const index =
        messages.findIndex(
          (item) =>
            item.id ===
            message.id
        );


      if (index <= 0) {
        return;
      }


      /*
       * The message being regenerated
       * should be an assistant message.
       *
       * The user message immediately
       * before it is the message that
       * Gemini should regenerate.
       */

      const userMessage =
        messages[index - 1];


      if (
        userMessage.role !==
        "user"
      ) {
        return;
      }


      /*
       * Build history BEFORE the
       * selected user message.
       */

      const history =
        messages
          .slice(0, index - 1)
          .filter(
            (item) =>
              item.role ===
              "user" ||
              item.role ===
              "assistant"
          )
          .map(
            (item) => ({
              role:
                item.role,

              content:
                item.content,
            })
          );


      try {

        const result =
          await regenerateMessage(
            userMessage,
            selectedModel,
            {
              conversationId: activeConversation,
              conversationTitle: conversationTitle,
              history,
              attachments:
                userMessage.uploadedAttachments ||
                userMessage.attachments ||
                [],
            }
          );


        /*
         * Update sidebar state
         * after successful regeneration.
         */

        if (
          result &&
          result.assistantMessage
        ) {

          const updatedMessages =
            messages.map(
              (item) => {

                if (
                  item.id ===
                  result.assistantMessage.id
                ) {
                  return {
                    ...item,

                    ...result.assistantMessage,
                  };
                }

                return item;
              }
            );


          onConversationUpdate({

            ...(activeConversationData || {}),

            id:
              activeConversation,

            title:
              conversationTitle,

            messages:
              updatedMessages,

            updatedAt:
              new Date().toISOString(),
          });
        }

      } catch (error) {

        console.error(
          "Failed to regenerate message:",
          error
        );
      }
    };

  /*
   * EDIT USER MESSAGE
   */

  const handleEdit =
    async (
      message,
      newContent
    ) => {

      if (
        isLoading ||
        !newContent.trim()
      ) {
        return;
      }


      const messageIndex =
        messages.findIndex(
          (item) =>
            item.id ===
            message.id
        );


      if (
        messageIndex === -1
      ) {
        return;
      }


      /*
       * Build conversation history
       * before the edited message.
       */

      const history =
        messages
          .slice(0, messageIndex)
          .filter(
            (item) =>
              item.role ===
              "user" ||
              item.role ===
              "assistant"
          )
          .map(
            (item) => ({
              role:
                item.role,

              content:
                item.content,
            })
          );


      try {

        const result =
          await editMessage(
            message,
            newContent,
            selectedModel,
            {
              conversationId: activeConversation,
              conversationTitle: conversationTitle,
              history,
              attachments:
                message.uploadedAttachments ||
                message.attachments ||
                [],
            }
          );


        /*
         * Update sidebar state
         * after successful edit.
         */

        if (
          result &&
          result.userMessage &&
          result.assistantMessage
        ) {

          const updatedMessages =
            messages
              .slice(
                0,
                messageIndex
              );


          updatedMessages.push(
            result.userMessage
          );

          updatedMessages.push(
            result.assistantMessage
          );


          onConversationUpdate({

            ...(activeConversationData || {}),

            id:
              activeConversation,

            title:
              conversationTitle,

            messages:
              updatedMessages,

            updatedAt:
              new Date().toISOString(),
          });
        }

      } catch (error) {

        console.error(
          "Failed to edit message:",
          error
        );
      }
    };


  /*
   * WELCOME PROMPTS
   */

  const handlePromptClick =
    (prompt) => {
      handleNewMessage(prompt);
    };


  const hasMessages =
    messages.length > 0;


  return (
    <main
      className={`chat-layout ${sidebarCollapsed
        ? "sidebar-collapsed"
        : ""
        }`}
    >

      <ChatHeader
        title={
          conversationTitle
        }

        selectedModel={
          selectedModel
        }

        setSelectedModel={
          setSelectedModel
        }
      />


      <div className="chat-content">

        {!hasMessages ? (

          <WelcomeScreen
            onPromptClick={
              handlePromptClick
            }
          />

        ) : (

          <MessageList
            messages={
              messages
            }

            isLoading={
              isLoading
            }

            onRegenerate={
              handleRegenerate
            }

            onEdit={
              handleEdit
            }
          />

        )}

      </div>


      <ChatComposer
        onSend={
          handleNewMessage
        }

        onStop={
          stopGeneration
        }

        disabled={
          isLoading
        }
      />

    </main>
  );
}


export default ChatLayout;